apiVersion: apps/v1
kind: Deployment
metadata:
  name: inspector
  labels:
    app: python-minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-minio
  template:
    metadata:
      labels:
        app: python-minio
    spec:
      containers:
        - name: python-script
          image: ggrig/k8-traffic:python
          env:
            - name: SOURCE_MINIO_URL
              value: "http://input-queue:9000"
            - name: SOURCE_MINIO_ACCESS_KEY
              value: minio1
            - name: SOURCE_MINIO_SECRET_KEY
              value: minio1@123
            - name: SOURCE_MINIO_BUCKET
              value: dummy
            # Source Minio Infromation
            - name: TARGET_MINIO_URL
              value: "http://output-queue:9000"
            - name: TARGET_MINIO_ACCESS_KEY
              value: minio2
            - name: TARGET_MINIO_SECRET_KEY
              value: minio2@123
            - name: TARGET_MINIO_BUCKET
              value: dummy
            # Log Level (Default to Info)
            - name: LOG_LEVEL
              value: info
