apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-drop-traffic-generator-backend
  labels:
    app: file-drop-traffic-generator-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-drop-traffic-generator-backend
  template:
    metadata:
      name: file-drop-traffic-generator-backend
      labels:
        app: file-drop-traffic-generator-backend
    spec:
      containers:
        - name: file-drop-traffic-generator-backend
          image: {{ .Values.backend.image.registry }}/{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /backend/health
              port: 5000
          env:
            - name: API_TOKEN
              value: {{ quote .Values.api.token }}
            - name: API_URL
              value: {{ quote .Values.api.url }}