apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
spec:
  rules:
    - http:
        paths:
          - path: /backend
            backend:
              serviceName: file-drop-traffic-generator-backend
              servicePort: 5000
          - path: /
            backend:
              serviceName: file-drop-traffic-generator-frontend
              servicePort: 80
