version: '3.6'
services:
  traffic_generator:
    image: traffic_generator
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - nextcloud
    environment:
      BASE_URL: "http://nextcloud"
      NC_USER: admin
      NC_PASSWORD: nextcloud@123
      TEST_ID: "1002"
      EXECUTABLE_PATH: "/usr/bin/google-chrome-stable"
    ports:
      - 8000:8000

  nextcloud:
    image: nextcloud:latest
    environment:
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: nextcloud@123
